#!/bin/bash

if ! [[ -v 1 ]]; then
    cat <<'DOC'
"Script management de la Plateforme Agréé Communautaire"

Usage:

    pdplibre command

The commands are:

    up              Start all services
    ps              Liste all services
    top             Top all services
    stop            Stop all services
    down            Down all services
    build           Build all images services
    push            Push all images services
    test            Lauch all test
    dc              docker compose
    pwd             Donne le répertoire de l'app
    install_script  Instal le script
DOC
exit
fi

SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
command cd $SCRIPT_DIR

dc() {
    init_docker
    docker compose "$@"
}

up() {
    init_docker
    docker compose up -d $@
}

ps() {
    init_docker
    docker compose ps $@
}

top() {
    init_docker
    docker compose top $@
}

stop() {
    init_docker
    docker compose stop $@
}

down() {
    init_docker
    docker compose down -v $@
}

build() {
    init_docker
    docker compose build 01-api-gateway
    docker compose build $@
}

push() {
    # Mettre un message attention avec une attente de réponse yes

    echo "ATTENTION: Vous êtes sur le point de partager les images docker à tout le monde"
    echo "Êtes-vous sûr de vouloir continuer? (yes/NO)"
    read -r response
    if [[ "$response" != "yes" ]]; then
        echo "Opération annulée."
        exit 1
    fi

    init_docker
    docker compose push $@
}

test() {
    init_docker
    docker compose run --rm test-bdd $@
}

pwd() {
    echo $SCRIPT_DIR
}

install_script() {
    ln -s $PWD/pdplibre ~/.local/bin/pdplibre
}

login_registry_pdplibre() {
    docker login git.pdplibre.org
}

test_auth_registry_pdplibre() {
    if ! grep -q git.pdplibre.org ~/.docker/config.json
    then
        echo "Authentifier sur le registre d'image docker git.phplibre.org"
        login_registry_pdplibre
    fi
}

init_docker() {
    cd docker
    test_auth_registry_pdplibre

    if [ ! -f secret ]; then
        echo "Init du fichier d'environnement secret"
        cp secret.example secret
    fi
}

cmd=$1
shift
$cmd $@

exit
