# SPDX-FileCopyrightText: 2026 Philippe ENTZMANN <philippe@entzmann.name>
#
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "01-api-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "01-api-gateway"
      app.kubernetes.io/instance: pac0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "01-api-gateway"
        app.kubernetes.io/instance: pac0
    spec:

      containers:
        - name: main
          image: astral/uv:python3.12-bookworm-slim
          imagePullPolicy: Always

          command: ["uvx"]
          args: ["--refresh", "pac0-cli@latest", "run", "1"]
          env:
          - name: NATS_URL
            value: "nats://s02-esb-central:4222"

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          #livenessProbe:
          #  httpGet:
          #    path: /healthcheck
          #    port: http
          #  initialDelaySeconds: 20
          #readinessProbe:
          #  httpGet:
          #    path: /healthcheck
          #    port: http
          #  initialDelaySeconds: 30

          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2048Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: s01-api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "01-api-gateway"
    app.kubernetes.io/instance: pac0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paxpar
  annotations:
    # uncomment staging or prod (not both !!)
    # comment both to disable let's encrypt certificate
    # to go back to the self-signed K8S certificate
    #cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-staging
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-prod
    
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    # see https://www.civo.com/learn/using-websockets-with-ingress-controller
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
      }
spec:
  tls:
    - hosts:      
      - pac01.document.legal
    # - host: pac02.document.legal
    # - host: pac03.document.legal
    # - host: pac04.document.legal
    # - host: pac0.document.legal
    #  - host: pac0.arundo.tech
      secretName: pac01-api-tls

  rules:
    - host: pac01.document.legal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s01-api-gateway
                port:
                  number: 8000
