apiVersion: apps/v1
kind: Deployment
metadata:
  name: 03-controle-formats
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: 03-controle-formats
      app.kubernetes.io/instance: pac0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 03-controle-formats
        app.kubernetes.io/instance: pac0
    spec:

      containers:
        - name: main
          image: astral/uv:python3.12-bookworm-slim
          command: ["uvx"]
          args: ["pac0-cli@latest", "run", "3"]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2048Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: 03-controle-formats
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: 03-controle-formats
    app.kubernetes.io/instance: pac0


