name: 🐛 Bug Report
description: Expliquez comment vous avez trouvé ce bug. 
body:
    # - type: input
    #   id: affected-versions
    #   attributes:
    #       label: Symfony version(s) affected
    #       placeholder: x.y.z
    #   validations:
    #       required: true
    - type: textarea
      id: description
      attributes:
         label: Description
         description: Une description claire et concise du problème
      validations:
        required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
            label: Comment reproduire
            description: |
             ⚠️  Ceci est la partie la plus importante du rapport ⚠️
             Sans un moyen facile de reproduire votre problème, nous aurons peu de chances de pouvoir vous aider et de corriger le bug.
             Veuillez prendre le temps de nous montrer du code et/ou une configuration nécessaire pour que d'autres puissent reproduire facilement le problème.
             La plupart du temps, créer un "bug reproducer" comme expliqué dans l'URL ci-dessous est la meilleure façon de nous aider
             et augmente les chances que quelqu'un y jette un œil :
             https://git.pdplibre.org/Construction_PA/PA_Communautaire/src/branch/main/docs/developpement/Contribuer.md
      validations:
            required: true
    - type: textarea
      id: possible-solution
      attributes:
            label: Solution Possible
            description: |
              Optionnel : uniquement si vous avez des suggestions sur un correctif/raison du bug
              N'hésitez pas à créer une pull request avec votre solution, cela aide à obtenir des commentaires plus rapides.
    - type: textarea
      id: additional-context
      attributes:
            label: Contexte Supplémentaire
            description: "Optionnel : tout autre contexte sur le problème : messages de journal, captures d'écran, etc."
