services:
  # 02-esb-central (NATS Server - Le pivot de communication)
  02-esb-central:
    image: nats:latest
    container_name: pac02-esb-central

  # 01-api-gateway (FastAPI)
  01-api-gateway:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac01-api-gateway
    entrypoint: uvx
    command: pac0-cli@latest run 1
    environment:
      - NATS_URL=nats://02-esb-central:4222
    ports:
      - "8000:8000"
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  # Services de traitement (FastStream)
  03-controle-formats:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac03-controle-formats
    entrypoint: uvx
    command: pac0-cli@latest run 3
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  04-validation-metier:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac04-validation-metier
    entrypoint: uvx
    command: pac0-cli@latest run 4
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  05-conversion-formats:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac05-conversion-formats
    entrypoint: uvx
    command: pac0-cli@latest run 5
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  06-annuaire-local:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac06-annuaire-local
    entrypoint: uvx
    command: pac0-cli@latest run 6
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  07-routage:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac07-routage
    entrypoint: uvx
    command: pac0-cli@latest run 7
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  08-transmission-fiscale:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac08-transmission-fiscale
    entrypoint: uvx
    command: pac0-cli@latest run 8
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

  09-gestion-cycle-vie:
    image: astral/uv:python3.12-bookworm-slim
    container_name: pac09-gestion-cycle-vie
    entrypoint: uvx
    command: pac0-cli@latest run 9
    environment:
      - NATS_URL=nats://02-esb-central:4222
    depends_on:
      - 02-esb-central
    volumes:
      - uv_cache:/root/.cache/uv

volumes:
  uv_cache: