import json
import logging
import sqlite3
from datetime import datetime
from pathlib import Path

import dateutil
import polars as pl

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.info("LOG !!!!")


def do(
    source: str,
    dest: str,
    delta: int,
    rebuild: bool = False,
    filter_member: list[str] | None = None,
):
    """
    Colonnes:
        - `id`: row id generated by the proxy
        - `m`: memberid from JWT payload
        - `t`: datetime of the request (YYYY-MM-DD HH:MM:SS)
        - `v`: verb of the request (GET, POST, PUT, DELETE,...)
        - `e`: endpoint of the request
        - `p`: path of the request
        - `s`: status code of the response (200, 400, ...)
        - `d`: duration of the request in milliseconds
        - `req.size`: size of the request in bytes
        - `res.size`: size of the response in bytes
        - `req.sha256`: SHA256 hash of the request
        - `res.sha256`: SHA256 hash of the response
    """
    x_month_ago = datetime.now() + dateutil.relativedelta.relativedelta(months=delta)
    # month prefix as 202603 (YYYYMM)
    year_month = f"{x_month_ago.year}{x_month_ago.month:02d}"
    dest_path = Path(dest)
    db_path = dest_path / f"{year_month}.pac0.db"
    logger.info(f"Report for {year_month} db_path={db_path}")

    if rebuild or not db_path.exists():
        logger.info(f"Rebuilding report for {year_month}")

        # remove/create a monthly sqlite database at `dest`
        dest_path.mkdir(parents=True, exist_ok=True)
        if db_path.exists():
            db_path.unlink()

        # write to a monthly sqlite database
        conn = sqlite3.connect(str(db_path))
        cursor = conn.cursor()

        # Create table schema
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS requests (
                id TEXT PRIMARY KEY,
                m TEXT,
                t TEXT,
                v TEXT,
                e TEXT,
                p TEXT,
                s INTEGER,
                d INTEGER,
                req_size INTEGER,
                res_size INTEGER,
                req_sha256 TEXT,
                res_sha256 TEXT
            )
        """)

        for f in Path(source).glob(f"{year_month}*.pac0"):
            # load file as json payload
            with open(f, "r") as fp:
                data = json.load(fp)

            # write to a monthly sqlite database
            cursor.execute(
                """
                INSERT INTO requests (id, m, t, v, e, p, s, d, req_size, res_size, req_sha256, res_sha256)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    data.get("id"),
                    data.get("m"),
                    data.get("t"),
                    data.get("v"),
                    data.get("e"),
                    data.get("p"),
                    data.get("s"),
                    data.get("d"),
                    data.get("req", {}).get("size"),
                    data.get("res", {}).get("size"),
                    data.get("req", {}).get("sha256"),
                    data.get("res", {}).get("sha256"),
                ),
            )

        conn.commit()
        conn.close()

    # sql query, group by `m` (memberid), filter by `filter_member`, fetch raw data
    # Then calculate aggregates with polars including percentiles
    conn = sqlite3.connect(str(db_path))
    query = """
        SELECT
            m as memberid,
            d as duration,
            req_size,
            res_size,
            s as status
        FROM requests
        WHERE 1=1
    """

    # if filter_member:
    #    placeholders = ",".join(["?" for _ in filter_member])
    #    query += f" AND m IN ({placeholders})"
    #
    # params = filter_member if filter_member else []

    # Fetch raw data
    df = pl.read_database(
        query,
        conn,
        # params=params,
    )
    conn.close()

    # Calculate aggregates and percentiles with polars
    result = (
        df.group_by("memberid")
        .agg(
            pl.col("duration").count().alias("nb_requests"),
            pl.col("duration").mean().alias("avg_duration"),
            pl.col("duration").max().alias("max_duration"),
            pl.col("duration").quantile(0.90, "nearest").alias("p90_duration"),
            pl.col("duration").quantile(0.99, "nearest").alias("p99_duration"),
            pl.col("duration").sum().alias("total_duration"),
            pl.col("status").ne(200).sum().alias("nb_errors"),
            pl.col("req_size").mean().alias("avg_req_size"),
            pl.col("res_size").mean().alias("avg_res_size"),
            pl.col("req_size").sum().alias("total_req_size"),
            pl.col("res_size").sum().alias("total_res_size"),
            (pl.col("req_size") + pl.col("res_size")).sum().alias("total_size"),
            pl.col("req_size").quantile(0.90, "nearest").alias("p90_req_size"),
            pl.col("req_size").quantile(0.99, "nearest").alias("p99_req_size"),
            pl.col("res_size").quantile(0.90, "nearest").alias("p90_res_size"),
            pl.col("res_size").quantile(0.99, "nearest").alias("p99_res_size"),
        )
        .sort("nb_requests", descending=True)
    )

    # return as a polars dataframe
    return result


def do_old(
    source: str,
    dest: str,
    year_month: str | None = None,
    rebuild: bool = False,
    filter_member: list[str] | None = None,
):
    """
    Colonnes:
        - `id`: row id generated by the proxy
        - `m`: memberid from JWT payload
        - `t`: datetime of the request (YYYY-MM-DD HH:MM:SS)
        - `v`: verb of the request (GET, POST, PUT, DELETE,...)
        - `e`: endpoint of the request
        - `p`: path of the request
        - `s`: status code of the response (200, 400, ...)
        - `d`: duration of the request in milliseconds
        - `req.size`: size of the request in bytes
        - `res.size`: size of the response in bytes
        - `req.sha256`: SHA256 hash of the request
        - `res.sha256`: SHA256 hash of the response
    """
    if year_month is None:
        # d = datetime.strptime("2013-03-31", "%Y-%m-%d")
        one_month_ago = datetime.now() - dateutil.relativedelta.relativedelta(months=1)
        # month prefix as 202603 (YYYYMM)
        year_month = f"{one_month_ago.year}{one_month_ago.month:02d}"
    # TODO: in v2 adapt for s3
    # source_mounth_filter = Path(source) / one_month_ago.year f"{month_date_prefix}*.pac0"
    #

    dest_path = Path(dest)
    db_path = dest_path / f"{year_month}.pac0.db"

    if rebuild or not db_path.exists():
        # remove/create a monthly sqlite database at `dest`
        dest_path.mkdir(parents=True, exist_ok=True)
        if db_path.exists():
            db_path.unlink()

        # load file as json payload
        # write to a monthly sqlite database
        conn = sqlite3.connect(str(db_path))
        cursor = conn.cursor()

        # Create table schema
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS requests (
                id INTEGER PRIMARY KEY,
                m TEXT,
                t TEXT,
                v TEXT,
                e TEXT,
                p TEXT,
                s INTEGER,
                d INTEGER,
                req_size INTEGER,
                res_size INTEGER,
                req_sha256 TEXT,
                res_sha256 TEXT
            )
        """)

        for f in Path(source).glob(f"{year_month}*.pac0"):
            # load file as json payload
            with open(f, "r") as fp:
                data = json.load(fp)

            # write to a monthly sqlite database
            if isinstance(data, list):
                cursor.executemany(
                    """
                    INSERT INTO requests (id, m, t, v, e, p, s, d, req_size, res_size, req_sha256, res_sha256)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    [
                        (
                            r.get("id"),
                            r.get("m"),
                            r.get("t"),
                            r.get("v"),
                            r.get("e"),
                            r.get("p"),
                            r.get("s"),
                            r.get("d"),
                            r.get("req.size"),
                            r.get("res.size"),
                            r.get("req.sha256"),
                            r.get("res.sha256"),
                        )
                        for r in data
                    ],
                )

        conn.commit()
        conn.close()

    # sql query, group by `m` (memberid), filter by `filter_member`, fetch raw data
    # Then calculate aggregates with polars including percentiles

    conn = sqlite3.connect(str(db_path))

    query = """
        SELECT
            m as memberid,
            d as duration,
            req_size,
            res_size,
            s as status
        FROM requests
        WHERE 1=1
    """

    # if filter_member:
    #    placeholders = ",".join(["?" for _ in filter_member])
    #    query += f" AND m IN ({placeholders})"
    #
    # params = filter_member if filter_member else []

    # Fetch raw data
    df = pl.read_database(
        query,
        conn,
        # params=params,
    )
    conn.close()

    # Calculate aggregates and percentiles with polars
    result = (
        df.group_by("memberid")
        .agg(
            pl.col("duration").count().alias("nb_requests"),
            pl.col("duration").mean().alias("avg_duration"),
            pl.col("duration").max().alias("max_duration"),
            pl.col("duration").quantile(0.90, "nearest").alias("p90_duration"),
            pl.col("duration").quantile(0.99, "nearest").alias("p99_duration"),
            pl.col("duration").sum().alias("total_duration"),
            pl.col("status").ne(200).sum().alias("nb_errors"),
            pl.col("req_size").mean().alias("avg_req_size"),
            pl.col("res_size").mean().alias("avg_res_size"),
            pl.col("req_size").sum().alias("total_req_size"),
            pl.col("res_size").sum().alias("total_res_size"),
            (pl.col("req_size") + pl.col("res_size")).sum().alias("total_size"),
            pl.col("req_size").quantile(0.90, "nearest").alias("p90_req_size"),
            pl.col("req_size").quantile(0.99, "nearest").alias("p99_req_size"),
            pl.col("res_size").quantile(0.90, "nearest").alias("p90_res_size"),
            pl.col("res_size").quantile(0.99, "nearest").alias("p99_res_size"),
        )
        .sort("nb_requests", descending=True)
    )

    # return as a polars dataframe
    return result
